version: '3'
services:
  postgres_server:
    build: ./postgres_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    ports:
      - "5432:5432"

  postgres_client:
    build: ./postgres_client
    links:
      - postgres_server:db
